### PR TITLE
merge the 2 nixos services, generate 2 docker images

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Comment by rhyslbw** [comment]
The missing dependency reported in a [past PR review](https://github.com/input-output-hk/cardano-db-sync/pull/2#pullrequestreview-366780365) is still outstanding

**Comment by craigem** [comment]
> The missing dependency reported in a [past PR review](https://github.com/input-output-hk/cardano-db-sync/pull/2#pullrequestreview-366780365) is still outstanding

Commit 1262555 should address this.

**Comment by disassembler** [comment]
I'm merging. If there's more to do, it can be in a follow-up.

**Pull request merged**
