### PR TITLE
Update index state

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by erikd** [comment]
I have a WIP PR for this that ran into trouble with Allegra/Mary changes. I am about to release `6.0.0` and would prefer not to have Allegra/Mary changes in that release. My branch for this is `erikd/allegra-mary` and currently does not compile.

**Comment by erikd** [comment]
If you can bump `index-state` while avoiding Allegra/Mary then got for it.

**Comment by newhoggy** [comment]
I checked the history, and unfortunately this is not possible because the nothunk fixes in `cardano-node` that I need are rolled up into the same commit `bc97ebd1eb6cdd36efc1061234180f4f62bb54cc` as the Allegra/Mary changes.

**Comment by newhoggy** [comment]
I'll leave this PR parked until `6.0.0` is released.

**Comment by erikd** [comment]
It might make more sense just to deep six this PR in favor of my `erikd/allegra-mary` branch.

**Comment by erikd** [comment]
Index state has been updated in another PR and those dependency updates are almost certainly no longer relevant.

Closing this.

**Pull request closed without merging**
