### PR TITLE
Changelog and dependencies update for tag 13.0.0-rc4

### PR DESCRIPTION
**Pull request by kderme**

### CODE REVIEW

**Comment by erikd** [comment]
Code changes should be on `master` and then cherry picked onto the `release/13.0.x` branch. All change log changes should remain on the `release/13.0.x` branch until after the actual release. This process is documented in https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/release-process.md

**Comment by erikd** [comment]
Most of the changes on this branch were pulled into PR #1161 .

**Comment by kderme** [comment]
I don't see the reason not to have the changelog on master for changes that are already on master. IMO carrying around the changelog on a release branch is causing many unnecessatry conflicts.

**Comment by erikd** [comment]
Changelog on master means a constant stream of merge conflicts.

**Comment by erikd** [comment]
Superceded.

**Pull request closed without merging**
