### PR TITLE
Avoid Rollbacks during restart

### PR DESCRIPTION
**Pull request by kderme**
Fixes https://github.com/input-output-hk/cardano-db-sync/issues/1190
This should drastically speed up restart times.
Still draft as it needs a lot of testing.

Currently when there is a restart, db-sync goes back to the latest on disk ledger snapshot. It also deletes all data in the db back to this point as it maintains the property that ledger and db are always at the same point. However in most cases deleting the db is unnecessary and db-sync has to reinsert all the deleted data, which may take long if many blocks are deleted.

With this pr we change the property: it is now that the db tip point is never behind the ledger. So on a relatively long rollback received from the chainsync server, db-sync won't delete any db-blocks. It will apply each new block to the ledger state and it will check if the block is already in the db. If it's already there it just goes to the next block. If it's not, it first cleans up the db for any existing blocks with greater or equal BlockNo and then inserts the block. After that the initial property, ledger and db at the same point, is restored.

As an optimization, when db-sync doesn't do a full rollback, ie doesn't delete the db, it will change its `ConsistentLevel` to `DBAheadOfLedger`. When the consistency between ledger and db is restored it will change the level back to `Consistent`. The query I mentioned above only happens with `DBAheadOfLedger`, so in the normal syncing case no additional queries are executed.

### CODE REVIEW

**Comment by erikd** [comment]
How does it avoid rollbacks?

**Comment by kderme** [comment]
> How does it avoid rollbacks?

I added a description. In short db-sync will not delete a block from the db until the time that itself recognises that there is a fork, ie different block with the same BlockNo and not when the node sends a Rollback message.

**Comment by erikd** [comment]
Would be really nice to delete the description above and put in in the commit message so we have a permanent record of it in the Git repo rather than here on Github

> .It will apply each new block to the ledger state and it will check if the block is already in the db. If it's already there it just goes to the next block.

I assume it also needs to act on all the ledger events. Is that what it does? If it gets a block that is already in the db, but the ledger state emits and event containing say rewards, wouldn't those rewards already be in the db? Does it check to see if they are already there and avoid inserting them again?

**Comment by kderme** [comment]
If the block hash is there it assumes ledger events have also been inserted, so it does nothing else with the block and ignores the events.

**Comment by erikd** [comment]
ok, would like to see a notes to this effect added to the commit message. The commit message can be a lot briefer than what you have above.

**Pull request merged**
