### PR TITLE
Fix bug 'Restart causes a resync from genesis'

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by islishude** [comment]
Can you patch this to v7?

**Comment by erikd** [comment]
@islishude This was never a problem with `7.*`. From the commit message, this fixes a bug in ceb2e38 but that commit was never in `7.*`

**Comment by islishude** [comment]
when I restart the service,It reports flowing log and takes so many time,I have to delete all data and resync.

I have met this two times.

```
dbsync_1          | [db-sync-node.Mux:Info:95] [2021-01-29 06:06:50.74 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Handshake Client end, duration 0.003558267s
dbsync_1          | [db-sync-node.Mux:Info:96] [2021-01-29 06:06:50.75 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: State: Mature
dbsync_1          | [db-sync-node:Info:99] [2021-01-29 06:06:50.75 UTC] Starting chainSyncClient
dbsync_1          | [db-sync-node:Info:99] [2021-01-29 06:06:50.76 UTC] Database tip is at slot 20333184, block 5271518
dbsync_1          | [db-sync-node:Info:104] [2021-01-29 06:06:50.76 UTC] Running DB thread
dbsync_1          | [db-sync-node.Subscription:Notice:31] [2021-01-29 06:06:50.77 UTC] [String "Required subscriptions started",String "SubscriptionTrace"]
dbsync_1          | [db-sync-node:Info:104] [2021-01-29 06:06:50.83 UTC] Rolling back to slot 0, hash f0f7892b5c333cffc4b3c4344de48af4cc63f55e44936196f365a9ef2244134f
dbsync_1          | [db-sync-node:Info:107] [2021-01-29 06:06:50.84 UTC] getHistoryInterpreter: acquired
^@dbsync_1          | [db-sync-node:Error:104] [2021-01-29 06:07:04.55 UTC] Rollback block count is high and therefore rollback is likely to be incredibly slow. Dropping the database and resyncing from scratch will be faster.
dbsync_1          | [db-sync-node:Info:104] [2021-01-29 06:07:32.86 UTC] Deleting slots numbered: [20333184..1]
```

**Comment by erikd** [comment]
That is fixed in `8.0.0` .

**Comment by islishude** [comment]
@erikd 8.0 still delete all data when restart

```
dbsync_1          | /run/secrets
dbsync_1          | Generating PGPASS file
dbsync_1          | Connecting to network: mainnet
dbsync_1          | [db-sync-node:Info:4] [2021-02-02 12:36:44.69 UTC] NetworkMagic: 764824073
dbsync_1          | [db-sync-node:Info:4] [2021-02-02 12:36:44.84 UTC] Initial genesis distribution present and correct
dbsync_1          | [db-sync-node:Info:4] [2021-02-02 12:36:44.84 UTC] Total genesis supply of Ada: 31112484745.000000
dbsync_1          | [db-sync-node:Info:4] [2021-02-02 12:36:44.85 UTC] Inserting Shelley Genesis distribution
dbsync_1          | [db-sync-node:Info:4] [2021-02-02 12:36:44.86 UTC] epochPluginOnStartup: Checking
dbsync_1          | [db-sync-node:Info:4] [2021-02-02 12:36:45.36 UTC] localInitiatorNetworkApplication: connecting to node via "/node-ipc/node.socket"
dbsync_1          | [db-sync-node.Subscription:Notice:41] [2021-02-02 12:36:45.36 UTC] Identity Starting Subscription Worker, valency 1
dbsync_1          | [db-sync-node.Subscription:Notice:42] [2021-02-02 12:36:45.37 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
dbsync_1          | [db-sync-node.Subscription:Notice:42] [2021-02-02 12:36:45.37 UTC] Identity Connection Attempt End, destination LocalAddress "/node-ipc/node.socket" outcome: ConnectSuccessLast
dbsync_1          | [db-sync-node.Handshake:Info:42] [2021-02-02 12:36:45.37 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 764824073),(NodeToClientV_2,TInt 764824073),(NodeToClientV_3,TInt 764824073),(NodeToClientV_4,TInt 764824073),(NodeToClientV_5,TInt 764824073),(NodeToClientV_6,TInt 764824073),(NodeToClientV_7,TInt 764824073),(NodeToClientV_8,TInt 764824073)]))
dbsync_1          | [db-sync-node.Handshake:Info:42] [2021-02-02 12:36:45.37 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_8 (TInt 764824073))
dbsync_1          | [db-sync-node.Mux:Info:42] [2021-02-02 12:36:45.37 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Handshake Client end, duration 0.000998513s
dbsync_1          | [db-sync-node.Mux:Info:44] [2021-02-02 12:36:45.37 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: State: Mature
dbsync_1          | [db-sync-node:Info:47] [2021-02-02 12:36:45.37 UTC] Starting chainSyncClient
dbsync_1          | [db-sync-node.Subscription:Notice:41] [2021-02-02 12:36:45.39 UTC] Identity Required subscriptions started
dbsync_1          | [db-sync-node:Info:47] [2021-02-02 12:36:45.40 UTC] Database tip is at slot 20702509, block 5289776
dbsync_1          | [db-sync-node:Info:51] [2021-02-02 12:36:45.40 UTC] Running DB thread
dbsync_1          | [db-sync-node:Info:54] [2021-02-02 12:36:45.46 UTC] getHistoryInterpreter: acquired
dbsync_1          | [db-sync-node:Info:51] [2021-02-02 12:36:45.46 UTC] Rolling back to slot 0, hash f0f7892b5c333cffc4b3c4344de48af4cc63f55e44936196f365a9ef2244134f
dbsync_1          | [db-sync-node:Info:51] [2021-02-02 12:37:13.49 UTC] Deleting slots numbered: [20702509..1]
```

**Comment by erikd** [comment]
Did you drop and recreate the database when you switched to version 8.0.0? That requirement is specified in the [changelog](https://github.com/input-output-hk/cardano-db-sync/releases/tag/8.0.0).

**Comment by islishude** [comment]
> Did you drop and recreate the database when you switched to version 8.0.0? That requirement is specified in the [changelog](https://github.com/input-output-hk/cardano-db-sync/releases/tag/8.0.0).

yes,of course

**Comment by islishude** [comment]
I may have found the reason,db-sync only handles SIGINT to graceful stop,but default stop signal of docker is SIGTERM,after grace period (10s for docker),docker sends SIGKILL to db-sync.

**Comment by islishude** [comment]
use SIGINT not works.

```
dbsync_1          | [db-sync-node.Subscription:Notice:139] [2021-02-03 02:49:28.90 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
dbsync_1          | [db-sync-node.Subscription:Error:139] [2021-02-03 02:49:28.90 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 13>: does not exist (No such file or directory)
dbsync_1          | [db-sync-node.ErrorPolicy:Warning:4] [2021-02-03 02:49:28.90 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 13>: does not exist (No such file or directory))) 20s 20s
dbsync_1          | [db-sync-node.Subscription:Warning:41] [2021-02-03 02:49:28.92 UTC] Identity Failed to start all required subscriptions
dbsync_1          | [db-sync-node.Subscription:Notice:41] [2021-02-03 02:49:29.92 UTC] Identity Restarting Subscription after 1.026317663s desired valency 1 current valency 0
dbsync_1          | [db-sync-node.Subscription:Notice:41] [2021-02-03 02:49:38.91 UTC] Identity Starting Subscription Worker, valency 1
dbsync_1          | [db-sync-node.Subscription:Notice:141] [2021-02-03 02:49:38.91 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
dbsync_1          | [db-sync-node.Subscription:Error:141] [2021-02-03 02:49:38.91 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 13>: does not exist (No such file or directory)
dbsync_1          | [db-sync-node.ErrorPolicy:Warning:4] [2021-02-03 02:49:38.91 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 13>: does not exist (No such file or directory))) 20s 20s
dbsync_1          | [db-sync-node.Subscription:Warning:41] [2021-02-03 02:49:38.93 UTC] Identity Failed to start all required subscriptions
dbsync_1          | [db-sync-node.Subscription:Notice:41] [2021-02-03 02:49:39.93 UTC] Identity Restarting Subscription after 1.02649473s desired valency 1 current valency 0
dbsync_1          | [db-sync-node.Subscription:Notice:41] [2021-02-03 02:49:48.91 UTC] Identity Starting Subscription Worker, valency 1
dbsync_1          | [db-sync-node.Subscription:Notice:143] [2021-02-03 02:49:48.91 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
dbsync_1          | [db-sync-node.Subscription:Notice:143] [2021-02-03 02:49:48.91 UTC] Identity Connection Attempt End, destination LocalAddress "/node-ipc/node.socket" outcome: ConnectSuccessLast
dbsync_1          | [db-sync-node.Handshake:Info:143] [2021-02-03 02:49:48.91 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 764824073),(NodeToClientV_2,TInt 764824073),(NodeToClientV_3,TInt 764824073),(NodeToClientV_4,TInt 764824073),(NodeToClientV_5,TInt 764824073),(NodeToClientV_6,TInt 764824073),(NodeToClientV_7,TInt 764824073),(NodeToClientV_8,TInt 764824073)]))
dbsync_1          | [db-sync-node.Handshake:Info:143] [2021-02-03 02:49:48.91 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_8 (TInt 764824073))
dbsync_1          | [db-sync-node.Mux:Info:143] [2021-02-03 02:49:48.91 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Handshake Client end, duration 0.001969764s
dbsync_1          | [db-sync-node.Mux:Info:144] [2021-02-03 02:49:48.91 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: State: Mature
dbsync_1          | [db-sync-node:Info:147] [2021-02-03 02:49:48.91 UTC] Starting chainSyncClient
dbsync_1          | [db-sync-node.Subscription:Notice:41] [2021-02-03 02:49:48.93 UTC] Identity Required subscriptions started
dbsync_1          | [db-sync-node:Info:147] [2021-02-03 02:49:48.95 UTC] Database tip is at slot 14823133, block 5000232
dbsync_1          | [db-sync-node:Info:151] [2021-02-03 02:49:48.95 UTC] Running DB thread
dbsync_1          | [db-sync-node:Info:151] [2021-02-03 02:49:49.18 UTC] Rolling back to slot 0, hash f0f7892b5c333cffc4b3c4344de48af4cc63f55e44936196f365a9ef2244134f
dbsync_1          | [db-sync-node:Info:154] [2021-02-03 02:49:49.18 UTC] getHistoryInterpreter: acquired
dbsync_1          | [db-sync-node:Info:151] [2021-02-03 02:50:14.27 UTC] Deleting slots numbered: [14823133..1]
```

**Comment by erikd** [comment]
@islishude Are you using the `docker-compose.yml` docker spec in the `db-sync` repo or something you have rolled yourself?

**Comment by islishude** [comment]
checked,I don't mount `/var/lib/cdbsync`

**Comment by erikd** [comment]
I know nothing about docker, but I do know that `db-sync` needs the directory pointed to by `--state-dir` be persistent.

**Comment by islishude** [comment]
that was my mistake, and it should be fixed now.

**Pull request merged**
