### PR TITLE
Readme.md: Update System Requirements

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Review by Cmdv — APPROVED** [review]
LGTM :shipit:

**Comment by erikd** [comment]
I updated the `Readme` and CI fails????

**Comment by erikd** [comment]
Since this is only the Readme I am going to merge this anyway.

**Comment by Cmdv** [comment]
CI always fails it seems, which is indicative of a CI but it would be nice for it not to fail 😅

**Pull request merged**
