### PR TITLE
Version 6.0.0

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Review by rhyslbw — APPROVED** [review]

**Review by rhyslbw — CHANGES_REQUESTED** [review]
A data volume needs to be added to the docker-compose file for the local state

**Comment by erikd** [comment]
@rhyslbw please feel free to push a commit to this branch.

**Review by rhyslbw — APPROVED** [review]

**Review by tatyanavych — APPROVED** [review]

**Review by ArturWieczorek — APPROVED** [review]

**Review by dcoutts — APPROVED** [review]
LGTM

**Comment by dcoutts** [comment]
bors merge

**Pull request merged**
