### PR TITLE
Tweak migration validation

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Review by tmcgilchrist — APPROVED** [review]
Looks good, thanks @erikd

**Comment by tienna** [comment]
I have the similar issue with dbsync 13.0.4, What should I do now? thank you

[db-sync-node:Error:6] [2022-08-22 09:56:39.57 UTC] Inconsistent migrations found:
Migrations missing at runtime that were present at compilation time: ["migration-1-0000-20190730.sql","migration-1-0001-20190730.sql","migration-1-0002-20190912.sql","migration-1-0003-20200211.sql","migration-1-0004-20201026.sql","migration-1-0005-20210311.sql","migration-1-0006-20210531.sql","migration-1-0007-20210611.sql","migration-1-0008-20210727.sql","migration-1-0009-20210727.sql","migration-2-0001-20211003.sql","migration-2-0002-20211007.sql","migration-2-0003-20211013.sql","migration-2-0004-20211014.sql","migration-2-0005-20211018.sql","migration-3-0001-20190816.sql","migration-3-0002-20200521.sql","migration-3-0003-20200702.sql","migration-3-0004-20200810.sql","migration-3-0005-20210116.sql","migration-3-0006-20210116.sql","migration-3-0007-20211022.sql","migration-3-9999-20200728.sql"]
Migrations found at runtime that were missing at compilation time: []
cardano-db-sync-extended: FatalError {fatalErrorMessage = "Inconsistent migrations found: \nMigrations missing at runtime that were present at compilation time: [\"migration-1-0000-20190730.sql\",\"migration-1-0001-20190730.sql\",\"migration-1-0002-20190912.sql\",\"migration-1-0003-20200211.sql\",\"migration-1-0004-20201026.sql\",\"migration-1-0005-20210311.sql\",\"migration-1-0006-20210531.sql\",\"migration-1-0007-20210611.sql\",\"migration-1-0008-20210727.sql\",\"migration-1-0009-20210727.sql\",\"migration-2-0001-20211003.sql\",\"migration-2-0002-20211007.sql\",\"migration-2-0003-20211013.sql\",\"migration-2-0004-20211014.sql\",\"migration-2-0005-20211018.sql\",\"migration-3-0001-20190816.sql\",\"migration-3-0002-20200521.sql\",\"migration-3-0003-20200702.sql\",\"migration-3-0004-20200810.sql\",\"migration-3-0005-20210116.sql\",\"migration-3-0006-20210116.sql\",\"migration-3-0007-20211022.sql\",\"migration-3-9999-20200728.sql\"]\nMigrations found at runtime that were missing at compilation time: []"}

**Comment by erikd** [comment]
@tienna You are seeing this because the schema files do not match the files expected by the `db-sync` executable.

You did not specify how you are installing `db-sync` so I cannot help more than that,

**Comment by tienna** [comment]
> @tienna You are seeing this because the schema files do not match the files expected by the `db-sync` executable.
> 
> You did not specify how you are installing `db-sync` so I cannot help more than that, Bottom line is that the schema files **MUST** be from the same version as `db-sync`.

Thank Erikd,
db-sync was installed by following steps in [this](https://cardano-community.github.io/guild-operators/Build/dbsync/).


_git fetch --tags --all
git pull_
_# Include the cardano-crypto-praos and libsodium components for db-sync
# On CentOS 7 (GCC 4.8.5) we should also do
# echo -e "package cryptonite\n  flags: -use_target_attributes" >> cabal.project.local
# Replace tag against checkout if you do not want to build the latest released version
git checkout $(curl -s https://api.github.com/repos/input-output-hk/cardano-db-sync/releases/latest | jq -r .tag_name)
# Use `-l` argument if you'd like to use system libsodium instead of IOG fork of libsodium while compiling
$CNODE_HOME/scripts/cabal-build-all.sh_

Regards
Tien

**Comment by erikd** [comment]
If you were following those steps exactly you should not be seeing this problem. 

I suspect that you are checking out a tag, building it and then switching back to the master branch (for which the schema files are different) before running it. If you run `db-sync` from a git checkout at a specific tag, you must run it at the same tag.

**Pull request merged**
