### PR TITLE
Tech debt

### PR DESCRIPTION
**Pull request by kderme**
https://github.com/input-output-hk/cardano-db-sync/issues/1274

### CODE REVIEW

**Comment by erikd** [comment]
> * Remove unused queries

These queries you a deleting were designed to be examples. I can't see the point of removing compiler checked documentation.

> *Use a single import group instead of splitting them with empty lines

This was done for readability.

> * Annotate queries based on their usage

I would actually call this document or comment rather than "annotate" but sure.

**Comment by kderme** [comment]
> > * Remove unused queries
> 
> These queries you a deleting were designed to be examples. I can't see the point of removing compiler checked documentation.

I think they are mostly leftovers and identical to other queries, so not sure how much they offer in terms of documentation. Also devs can always resurect them from git history.

If there is some specific query that you believe is worth keeping, of course we can.

> > *Use a single import group instead of splitting them with empty lines
> 
> This was done for readability.

Yes, but I think since db-sync has a big amount of dependencies, this is getting really hard to maintain.

**Comment by erikd** [comment]
> Yes, but I think since db-sync has a big amount of dependencies, this is getting really hard to maintain.

A lot of this is due to `ledger`, `consensus` and `network` actually lacking usable APIs.

**Comment by kderme** [comment]
Superseded by https://github.com/input-output-hk/cardano-db-sync/pull/1334

**Pull request closed without merging**
