### PR TITLE
doc/interesting-queries.md: Add new query

### PR DESCRIPTION
**Pull request by erikd**
This query finds incorrect epoch table entries.

Related to: https://github.com/input-output-hk/cardano-db-sync/issues/1457

### CODE REVIEW

**Review by Cmdv — COMMENTED** [review]
LGTM, though we should maybe add a caveat that this query is likely to be very slow over a big data set?

**Comment by erikd** [comment]
This query runs in under 10 seconds on a full `mainnet` database.

**Comment by Cmdv** [comment]
yeah cool, as mentioned in the issue I "think" that when my PR is released then this issue shouldn't exist.

**Review by Cmdv — APPROVED** [review]
LGTM 👍

**Pull request merged**
